# Generated by Django 5.0.6 on 2024-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_genre_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='rating_music',
        ),
        migrations.AddField(
            model_name='review',
            name='rating_cover',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_art/<django.db.models.fields.CharField>'),
        ),
    ]
