# Generated by Django 5.0.6 on 2024-10-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_rename_comment_review_content_review_album_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='favorite_track_id',
            new_name='favorite_track',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='worst_track_id',
            new_name='worst_track',
        ),
    ]
