# Generated by Django 5.1 on 2024-10-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_app", "0006_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
