# Generated by Django 5.1 on 2024-11-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_app", "0007_alter_track_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="favorite_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorite_review",
                to="review_app.track",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="worst_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worst_review",
                to="review_app.track",
            ),
        ),
    ]
