# Generated by Django 5.1 on 2025-05-04 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_app", "0008_alter_review_favorite_track_alter_review_worst_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="favorite_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_favtrack",
                to="review_app.track",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="worst_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_worsttrack",
                to="review_app.track",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_number",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editions",
                        to="review_app.album",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "album"],
                "unique_together": {("year", "album")},
            },
        ),
    ]
