# Generated by Django 5.1 on 2025-05-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "review_app",
            "0009_alter_review_favorite_track_alter_review_worst_track_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("spotify", "Spotify"),
                            ("tidal", "Tidal"),
                            ("apple_music", "Apple Music"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="review_app.album",
                    ),
                ),
            ],
            options={
                "unique_together": {("album", "link_type", "url")},
            },
        ),
    ]
