# Generated by Django 5.1 on 2025-05-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review_app", "0010_albumlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="albumlink",
            name="title",
        ),
    ]
